

spring:
  datasource:
    url: jdbc:mysql://10.6.172.174:3306/info_publish?serverTimezone=Asia/Shanghai&useUnicode=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    driver-class-name: com.mysql.cj.jdbc.Driver #oracle.jdbc.driver.OracleDriver
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 8
      maximum-pool-size: 16
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariDataPool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1 from dual

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  #type-aliases-package: com.example.domain.model
  #type-handlers-package: com.example.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
server:
  port: 8011