
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/admin_auth?serverTimezone=Asia/Shanghai&useUnicode=true&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver #oracle.jdbc.driver.OracleDriver
    username: root
    password: 123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 8
      maximum-pool-size: 16
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariDataPool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1 from dual

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false

  redis:
    database: 0
    host: localhost
    port: 6379
    password:      # 密码（默认为空）
    timeout: 6000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接


app:
  encrypt:
    salt: a23d1cd
    iteration: 2

  jwt:
    secret: 1a2z8k5dp9s3v
    expire: 3600
    header: token

server:
  port: 9002